version: "3.9"
services:
  fastapi-service:
    build:
      context: ./fast_api_server
    ports:
      - "8000:8000"
    volumes:
      - uploaded_files:/uploaded_files

  uploader-service:
    build:
      context: ./python_script_upload
    depends_on:
      - fastapi-service
    volumes:
      - ./python_script_upload:/app  # For accessing sample.pdf

volumes:
  uploaded_files:
