services:
  logging_fastapi_server:
    build:
      context: ./Logging_Service
    volumes:
      - uploads:/app/log_directory
    ports:
      - "7404:7404"

  fast_api_server_dummy:
    build:
      context: ./dummy_api_service
    ports:
      - "7408:7408"
    depends_on:
      - logging_fastapi_server
  
  python_service_files:
    build:
      context: ./service_log_files
    depends_on:
      - logging_fastapi_server

volumes:
  uploads:

