services:
  fast_api_server:
    build:
      context: ./Logging01
    volumes:
      - uploads:/app/log_directory
    ports:
      - "8000:8000"

  fast_api_server_dummy:
    build:
      context: ./dummy_api_service
    ports:
      - "8005:8005"
    depends_on:
      - fast_api_server
  
  python_script_upload:
    build:
      context: ./service_log_files
    depends_on:
      - fast_api_server

volumes:
  uploads:

