services:
  fast_api_server:
    build:
      context: ./Logging01
    volumes:
      - uploads:/app/log_directory
    ports:
      - "8000:8000"
  
  python_script_upload:
    build:
      context: ./service_log_files
    depends_on:
      - fast_api_server

volumes:
  uploads:
