version: "3.9"
services:
  fastapi-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - uploaded_files:/uploaded_files

  uploader-service:
    build:
      context: .
      dockerfile: Dockerfile-uploader
    depends_on:
      - fastapi-service

volumes:
  uploaded_files:
