services:
  logging_fastapi_server:
    build:
      context: ./Logging01
    volumes:
      - uploads:/app/log_directory
    ports:
      - "8000:8000"

  fast_api_server_dummy:
    build:
      context: ./dummy_api_service
    ports:
      - "8005:8005"
    depends_on:
      - logging_fastapi_server
  
  python_service_files:
    build:
      context: ./service_log_files
    depends_on:
      - logging_fastapi_server

volumes:
  uploads:

