services:
  fastapi_application:
    build:
      context: .
      dockerfile: Logging01/fastapi.Dockerfile
    container_name: fastapi_container
    networks:
      - my_network
    ports:
      - "8000:8000"
    volumes:
      - ./Logging01:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000
 
  service_log_files:
    build:
      context: .
      dockerfile: service_log_files/service.Dockerfile
    container_name: service_log_files_test
    networks:
      - my_network
    depends_on:
      - fastapi_application
    volumes:
      - ./service:/app
    command: python test_service01.py
 
networks:
  my_network:
    driver: bridge
